### ISSUE TITLE
Propose Logo/Icon

### ISSUE THREAD

**Issue by mirzazulfan** [Energizers/Energize#6]
Hi @Earu ,, I'm graphic disigner. I would like to know if you are interested that I make a logo for your project? If you allowed me, i"ll make logo for your project and it's free.

**Comment by Earu** [comment]
@mirzazulfan Sure why not go ahead! Always worth a shot.

**Comment by mirzazulfan** [comment]
Hi @Earu  I've designed a logo for your project. If you like it, you can use it. I'll send you files and pr. Tell me if you need some change, Thanks
![enegize](https://user-images.githubusercontent.com/36124339/40796170-61cdf71a-652e-11e8-960b-6dd2a48612e5.png)

**Comment by Earu** [comment]
Hey there @mirzazulfan , I like the [second logo you did](https://i.imgur.com/fd79CBX.png) but it is a bit bright, maybe you could come up with a dark gray gradient background and something like an [atom-like shape](https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Atom_editor_logo_black.svg/2000px-Atom_editor_logo_black.svg.png) instead of a lightning bolt? One of my other logos have a background I really like, maybe you could base yourself on [it](https://i.imgur.com/JM4lAWC.png), if you are still up to do that! Thanks in advance.

**Comment by mirzazulfan** [comment]
Like This @Earu 
![version 2](https://user-images.githubusercontent.com/36124339/40799670-7281daa4-6538-11e8-96ba-730c0fe3a0c5.png)

**Comment by Earu** [comment]
I really like those two:
 ![two](https://i.imgur.com/1YHKtIv.png) 
Could you scale them up?

**Comment by mirzazulfan** [comment]
I'm glad you liked it. How about this @Earu ? and tell me what size do you need ? 
![untitled-2](https://user-images.githubusercontent.com/36124339/40802187-1dff62e2-653f-11e8-9107-ea2029a9610a.png)

**Comment by Earu** [comment]
@mirzazulfan this is perfect, no need to to change it. Thanks a bunch!

**Comment by mirzazulfan** [comment]
You can download all files SVG, PDF, PNG. here : https://drive.google.com/drive/folders/1Y5goMhVynQjZ4kZ0CAh3RkA-RjVjve0V .
can you put the logo into readme file? that's enough for me. or may i create a pr ? thanks @Earu

**Comment by Earu** [comment]
@mirzazulfan sure! https://github.com/Earu/Energize/commit/69c00f3823c36910dd2e2ef488f8a7d730064d6d here it is.

**Comment by mirzazulfan** [comment]
:100: Thank you
